[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-ncnn-init-recognizer",
    "allow-ncnn-init-recognizer-from-asset",
    "allow-ncnn-init-microphone",
    "allow-ncnn-start-recognize",
    "allow-ncnn-stop-recognize"]
